name: 'Capture Ad-Shield remote token'
author: 'PiQuark6046, Adguard Software Ltd and contributors'

inputs:
  target:
    description: 'Target file'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install npm packages
      run: |
        npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run program
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        TARGET: ${{ inputs.target }}
      run: |
        npm run ci -- --token "$GITHUB_TOKEN" --repo "$REPO" --target "$TARGET"
      shell: bash
      working-directory: ${{ github.action_path }}